version: '3.8'
services:
  app:
    build: .
    ports:
      - ${API_PORT}:3000
    volumes:
      - /var/cause-connect-java-app:/home/deploy/cause-connect-java-app
    depends_on:
      - mysql
    stop_grace_period: 3s
    restart: unless-stopped
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
volumes:
  mysql_data: {}