version: '3'

services:
  dev-db:
      image: postgres:latest
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: Respons11
        POSTGRES_DB: maindatabase
      restart: always
      volumes:
        - horror-house-dev-db:/var/lib/postgresql/data
      networks:
        - horror-house-network

volumes:
  horror-house-dev-db:
networks:
  horror-house-network:
