version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql_dev_data:/var/lib/mysql
volumes:
  mysql_dev_data: {}
